import { Ticket, DashboardStats } from './types';

export const mockTickets: Ticket[] = [
  {
    id: 't001',
    title: 'Dashboard loading extremely slow',
    content: 'The main dashboard takes over 10 seconds to load. This is happening consistently for the past 3 days. We have a team of 50 users and everyone is experiencing this issue. This is severely impacting our productivity.',
    source: 'support',
    category: 'bug',
    friction_point: 'performance',
    sentiment: 'negative',
    sentiment_score: -0.85,
    urgency: 'critical',
    status: 'open',
    customer_name: 'John Smith',
    customer_email: 'john@acmecorp.com',
    ai_synopsis: 'Critical performance issue affecting 50-user team. Dashboard load times exceed 10 seconds, ongoing for 3 days.',
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    tags: ['performance', 'dashboard', 'urgent'],
  },
  {
    id: 't002',
    title: 'Feature Request: Dark mode support',
    content: 'Would love to see dark mode added to the application. Many of us work late hours and the bright interface causes eye strain. This would be a great quality of life improvement.',
    source: 'discord',
    category: 'feature_request',
    friction_point: 'ui_ux',
    sentiment: 'positive',
    sentiment_score: 0.65,
    urgency: 'low',
    status: 'open',
    customer_name: 'Sarah Chen',
    customer_email: 'sarah@devteam.io',
    ai_synopsis: 'User requests dark mode feature to reduce eye strain during late-night work sessions.',
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    tags: ['dark-mode', 'accessibility'],
  },
  {
    id: 't003',
    title: 'API rate limiting documentation unclear',
    content: 'I spent 2 hours trying to figure out the rate limits for the API. The documentation mentions limits but does not specify the exact numbers or how the sliding window works. Please clarify.',
    source: 'github',
    category: 'documentation',
    friction_point: 'confusing_docs',
    sentiment: 'negative',
    sentiment_score: -0.45,
    urgency: 'medium',
    status: 'open',
    customer_name: 'Mike Johnson',
    customer_email: 'mike@startup.co',
    ai_synopsis: 'Developer frustrated with unclear API rate limiting documentation. Requests specific numbers and sliding window explanation.',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['api', 'documentation'],
  },
  {
    id: 't004',
    title: 'Love the new analytics feature!',
    content: 'Just wanted to say the new analytics dashboard is amazing! The visualizations are beautiful and the data export feature saves us hours every week. Great job team!',
    source: 'twitter',
    category: 'other',
    friction_point: null,
    sentiment: 'positive',
    sentiment_score: 0.95,
    urgency: 'low',
    status: 'closed',
    customer_name: 'Emma Wilson',
    customer_email: 'emma@analytics.pro',
    ai_synopsis: 'Positive feedback praising new analytics dashboard. User highlights visualizations and time-saving data export.',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    tags: [],
  },
  {
    id: 't005',
    title: 'Integration with Slack not working',
    content: 'We set up the Slack integration following the docs but notifications are not coming through. We have verified the webhook URL and permissions. Need urgent help as we rely on this for alerts.',
    source: 'email',
    category: 'bug',
    friction_point: 'integration',
    sentiment: 'negative',
    sentiment_score: -0.70,
    urgency: 'high',
    status: 'in_progress',
    customer_name: 'David Lee',
    customer_email: 'david@techfirm.com',
    ai_synopsis: 'Slack integration failing despite correct setup. User verified webhook and permissions. Blocking alert workflow.',
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    tags: ['slack', 'integration', 'webhook'],
  },
  {
    id: 't006',
    title: 'Confusing onboarding flow',
    content: 'As a new user, I found the onboarding process very confusing. There are too many steps and its not clear what each setting does. I almost gave up before completing setup.',
    source: 'forum',
    category: 'ui_ux',
    friction_point: 'onboarding',
    sentiment: 'negative',
    sentiment_score: -0.55,
    urgency: 'medium',
    status: 'open',
    customer_name: 'Lisa Park',
    customer_email: 'lisa@newuser.net',
    ai_synopsis: 'New user nearly abandoned product due to complex onboarding. Too many unclear steps and settings.',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['ux', 'onboarding'],
  },
  {
    id: 't007',
    title: 'Request: Bulk import from CSV',
    content: 'We need to migrate 10,000 records from our old system. Currently we can only add items one by one through the UI. A CSV import feature would save us weeks of manual work.',
    source: 'support',
    category: 'feature_request',
    friction_point: 'missing_feature',
    sentiment: 'neutral',
    sentiment_score: 0.10,
    urgency: 'high',
    status: 'open',
    customer_name: 'Tom Brown',
    customer_email: 'tom@enterprise.org',
    ai_synopsis: 'Enterprise user needs bulk CSV import for 10K record migration. Current single-item UI is impractical.',
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['import', 'csv', 'migration'],
  },
  {
    id: 't008',
    title: 'Mobile app crashes on Android 14',
    content: 'The mobile app crashes immediately after login on Android 14 devices. Tested on Pixel 8 and Samsung S24. Worked fine on Android 13. Please fix ASAP.',
    source: 'github',
    category: 'bug',
    friction_point: 'performance',
    sentiment: 'negative',
    sentiment_score: -0.80,
    urgency: 'critical',
    status: 'open',
    customer_name: 'Alex Kim',
    customer_email: 'alex@mobiledev.io',
    ai_synopsis: 'Critical bug: App crashes post-login on Android 14. Confirmed on Pixel 8 and Samsung S24.',
    created_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    tags: ['mobile', 'android', 'crash'],
  },
  {
    id: 't009',
    title: 'Pricing tier confusion',
    content: 'The pricing page shows different features for Pro tier than what I actually get after subscribing. The comparison table needs to be updated to match reality.',
    source: 'email',
    category: 'documentation',
    friction_point: 'pricing',
    sentiment: 'negative',
    sentiment_score: -0.60,
    urgency: 'medium',
    status: 'open',
    customer_name: 'Rachel Green',
    customer_email: 'rachel@smb.com',
    ai_synopsis: 'Pricing page discrepancy: Pro tier features dont match actual subscription. Comparison table outdated.',
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    tags: [],
  },
  {
    id: 't010',
    title: 'Excellent customer support experience',
    content: 'Had an issue with billing and your support team resolved it within 30 minutes. Special thanks to Agent Maria who was incredibly helpful and patient. Will definitely recommend!',
    source: 'support',
    category: 'other',
    friction_point: null,
    sentiment: 'positive',
    sentiment_score: 0.90,
    urgency: 'low',
    status: 'resolved',
    customer_name: 'Chris Taylor',
    customer_email: 'chris@happycustomer.com',
    ai_synopsis: 'Glowing review of support experience. Billing issue resolved in 30 minutes. Agent Maria praised for helpfulness.',
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    tags: [],
  },
  {
    id: 't011',
    title: 'Keyboard shortcuts not working on Firefox',
    content: 'None of the keyboard shortcuts work when using Firefox 125. They work fine on Chrome. This is frustrating as I prefer Firefox for privacy reasons.',
    source: 'discord',
    category: 'bug',
    friction_point: 'ui_ux',
    sentiment: 'negative',
    sentiment_score: -0.50,
    urgency: 'medium',
    status: 'open',
    customer_name: 'Nina Patel',
    customer_email: 'nina@webdev.co',
    ai_synopsis: 'Firefox 125 compatibility issue: keyboard shortcuts non-functional. Works on Chrome. User prefers Firefox.',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['firefox', 'keyboard'],
  },
  {
    id: 't012',
    title: 'Need webhook retry mechanism',
    content: 'When our server is temporarily down, we lose webhook events permanently. Please add automatic retry with exponential backoff. This is standard practice for webhook implementations.',
    source: 'github',
    category: 'feature_request',
    friction_point: 'missing_feature',
    sentiment: 'neutral',
    sentiment_score: -0.20,
    urgency: 'high',
    status: 'open',
    customer_name: 'James Wilson',
    customer_email: 'james@backend.dev',
    ai_synopsis: 'Feature request: Webhook retry with exponential backoff. Currently events lost during server downtime.',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['webhook', 'reliability'],
  },
  {
    id: 't013',
    title: 'Search results are irrelevant',
    content: 'The search function returns completely unrelated results. Searching for "invoice" shows me user profiles and settings pages. The search algorithm needs improvement.',
    source: 'forum',
    category: 'bug',
    friction_point: 'ui_ux',
    sentiment: 'negative',
    sentiment_score: -0.65,
    urgency: 'medium',
    status: 'open',
    customer_name: 'Maria Garcia',
    customer_email: 'maria@searchtest.com',
    ai_synopsis: 'Search functionality broken: returns irrelevant results. Invoice search shows profiles and settings.',
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['search'],
  },
  {
    id: 't014',
    title: 'Great API documentation',
    content: 'Just integrated your API into our system. The documentation is excellent - clear examples, good error descriptions, and the Postman collection was super helpful. Thank you!',
    source: 'twitter',
    category: 'other',
    friction_point: null,
    sentiment: 'positive',
    sentiment_score: 0.85,
    urgency: 'low',
    status: 'closed',
    customer_name: 'Kevin Zhang',
    customer_email: 'kevin@integration.io',
    ai_synopsis: 'Positive API integration feedback. Documentation praised for clarity, examples, and Postman collection.',
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    tags: [],
  },
  {
    id: 't015',
    title: 'Two-factor authentication issues',
    content: 'After enabling 2FA, I sometimes dont receive the SMS code. Have to request multiple times. This is a security feature that needs to be reliable.',
    source: 'support',
    category: 'bug',
    friction_point: 'performance',
    sentiment: 'negative',
    sentiment_score: -0.70,
    urgency: 'high',
    status: 'open',
    customer_name: 'Amy Foster',
    customer_email: 'amy@security.net',
    ai_synopsis: 'Intermittent 2FA SMS delivery failure. User must request codes multiple times. Security reliability concern.',
    created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    tags: ['2fa', 'sms'],
  },
];

export function calculateStats(tickets: Ticket[]): DashboardStats {
  const stats: DashboardStats = {
    total_tickets: tickets.length,
    open_tickets: tickets.filter(t => t.status === 'open').length,
    critical_tickets: tickets.filter(t => t.urgency === 'critical').length,
    avg_sentiment: 0,
    by_source: { support: 0, discord: 0, github: 0, email: 0, twitter: 0, forum: 0, other: 0 },
    by_category: { bug: 0, feature_request: 0, ui_ux: 0, performance: 0, documentation: 0, question: 0, other: 0 },
    by_sentiment: { positive: 0, negative: 0, neutral: 0 },
    by_urgency: { low: 0, medium: 0, high: 0, critical: 0 },
    by_friction_point: {},
    recent_trend: [],
  };

  let totalSentiment = 0;

  tickets.forEach(ticket => {
    stats.by_source[ticket.source]++;
    stats.by_category[ticket.category]++;
    stats.by_sentiment[ticket.sentiment]++;
    stats.by_urgency[ticket.urgency]++;
    totalSentiment += ticket.sentiment_score;

    if (ticket.friction_point) {
      stats.by_friction_point[ticket.friction_point] = (stats.by_friction_point[ticket.friction_point] || 0) + 1;
    }
  });

  stats.avg_sentiment = tickets.length > 0 ? totalSentiment / tickets.length : 0;

  // Generate trend data for last 7 days
  for (let i = 6; i >= 0; i--) {
    const date = new Date();
    date.setDate(date.getDate() - i);
    const dateStr = date.toISOString().split('T')[0];
    
    const dayTickets = tickets.filter(t => {
      const ticketDate = new Date(t.created_at).toISOString().split('T')[0];
      return ticketDate === dateStr;
    });

    stats.recent_trend.push({
      date: dateStr,
      count: dayTickets.length,
      sentiment_avg: dayTickets.length > 0 
        ? dayTickets.reduce((sum, t) => sum + t.sentiment_score, 0) / dayTickets.length 
        : 0,
    });
  }

  return stats;
}
